# Generated by Django 6.0.3 on 2026-04-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TEXT_SUCCESS', 'Text Success'), ('FIRST_SUCCESS', 'First Success'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
