# Generated by Django 6.0.3 on 2026-04-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='creator',
        ),
        migrations.AddField(
            model_name='library',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='app.userprofile'),
        ),
    ]
