# Generated by Django 6.0.3 on 2026-04-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_library_creator_library_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
