# Generated by Django 6.0.3 on 2026-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_song_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='app.song'),
        ),
    ]
