# Generated by Django 6.0.3 on 2026-04-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='background_story',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='form',
            name='occasion',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='form',
            name='tone',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='form',
            name='vocal_style',
            field=models.CharField(default='Any', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='failure_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='parent_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='app.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='form',
            name='requested_duration_seconds',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
